<?PHP
$url="http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
		$file = dirname($url);
?>

<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 30px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Developers SAC</h1>
		<br>
        <div>Listado de empleados</div>
		<br>
		<form id="form1" name="form1" method="post" action="<?PHP echo $file ?>/busqueda">
		  Filtrar por correo 
		  <input type="text" name="correo" id="correo" />
		  <input type="submit" name="button" id="button" value="Buscar" />
		</form>
		
		<table border="1" cellpadding="3" cellspacing="0" align="center"  >
		<tr>
		<td>nombre</td>
		<td>Correo</td>
		<td>Posicion</td>
		<td>Salario</td>
		<td>Detalle</td>
		</tr>
		
		<?PHP
		
		
		foreach ($id as $person_name => $person_a) {
			echo "<tr>
			<td>".$person_a['name']."</td>
			<td>".$person_a['email']."</td>
			<td>".$person_a['position']."</td>
			<td>".$person_a['salary']."</td>
			<td><a href='".$file."/get/".$person_a['id']."'>Detalle</a></td>
			</tr>";
			
		}
		
		?>
		</table>
    </body>
</html>
